[package]
name = "wasi-guard"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmparser = "0.224.0"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0.95"
wasi-guard-macros = { path = "macros" }

[dev-dependencies]
wat = "1.225.0"

[workspace]
members = ["macros"]
resolver = "2"
