name: CI

on:
  push:
    branches:
      - main
      - static_params_type
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-07-26
          override: true

      - name: cargo registry cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: cargo build cache
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Run tests
        run: |
          cargo test
          cargo test --features wasmedge-sock

      - name: Macro tests
        run: |
          cd macros
          cargo test
          cargo test --features wasmedge-sock

      - name: WASI descriptor tests
        run: cd wasi_descriptor && cargo test

      - name: WASI tests
        run: |
          cd wasi
          cargo test
          cargo test --features wasmedge-sock

      - name: Examples
        run: cargo build --examples
